[development]
address = "localhost"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
template_dir = "templates/"

[staging]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
template_dir = "templates/"

[production]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "critical"
limits = { forms = 32768 }
template_dir = "templates/"
